#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Scraper\Command\UntappdCommand;

$application = new Application();
$application->add(new UntappdCommand());
$application->run();
